### ISSUE TITLE
Please make an example project!

### ISSUE THREAD

**Issue by giosamm** [thimenesup/GodotNFC#2]
First of all thank you for your work, but I am unable to implement it in Godot. Could you upload a project where the NFC module is already implemented? Thanks so much

**Comment by lentsius-bark** [comment]
@thimenesup I second what @GiovanniSammarchi mentioned above. I'm interested in implementing GodotNFC to have a way of sharing save games between players and an example project would really help! Thanks!

**Comment by Whitefame** [comment]
Yeah, this or some kind of dokumentation.

**Comment by DisDoh** [comment]
exactly a Readme with how to use would be nice

**Comment by thimenesup** [comment]
Should be fixed with 753e50a
